// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuYuzNXxW4O1Pw6cZE6Yyr8zkJ_ewI0gg',
    appId: '1:56808941433:web:44986fa3dc3cf7c371f1a8',
    messagingSenderId: '56808941433',
    projectId: 'mindease-562fa',
    authDomain: 'mindease-562fa.firebaseapp.com',
    storageBucket: 'mindease-562fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWEWAeJl5PF3sOWLRuSDCaRNeOdpF4EvQ',
    appId: '1:56808941433:android:bd5e3551f12ca88f71f1a8',
    messagingSenderId: '56808941433',
    projectId: 'mindease-562fa',
    storageBucket: 'mindease-562fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD47TGIUwpE8QtX66kymwRjcCJhCctUIEk',
    appId: '1:56808941433:ios:e4e8540ca5c0889c71f1a8',
    messagingSenderId: '56808941433',
    projectId: 'mindease-562fa',
    storageBucket: 'mindease-562fa.firebasestorage.app',
    iosBundleId: 'com.mindease.Ease.mindease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD47TGIUwpE8QtX66kymwRjcCJhCctUIEk',
    appId: '1:56808941433:ios:e4e8540ca5c0889c71f1a8',
    messagingSenderId: '56808941433',
    projectId: 'mindease-562fa',
    storageBucket: 'mindease-562fa.firebasestorage.app',
    iosBundleId: 'com.mindease.Ease.mindease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuYuzNXxW4O1Pw6cZE6Yyr8zkJ_ewI0gg',
    appId: '1:56808941433:web:57c1fbfc440ffe0471f1a8',
    messagingSenderId: '56808941433',
    projectId: 'mindease-562fa',
    authDomain: 'mindease-562fa.firebaseapp.com',
    storageBucket: 'mindease-562fa.firebasestorage.app',
  );
}
